TimeboardIO/timeboard

core-ui/pom.xml, pom.xml
=> Patch Jackson vulnerability

timesheet/src/main/resources/static/timesheet.js
=> Patch issues #35

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java, core/src/main/java/timeboard/core/internal/UserServiceImpl.java, timesheet/src/main/java/timeboard/timesheet/TimesheetValidationServlet.java
Add logs to all data modification on core services (not on simple access).
=>  Add logs to core services #28 

core/src/main/java/timeboard/core/internal/UserServiceImpl.java
=> Fix password change

core/pom.xml, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/internal/UserServiceImpl.java, core/src/main/java/timeboard/core/model/Project.java, core/src/main/java/timeboard/core/model/User.java, core/src/test/java/timeboard/core/internal/UserServiceImplTest.java, core/src/test/resources/META-INF/persistence.xml, scripts/sql/mysql8.sql
=> Fix issues#22

projects/src/main/java/timeboard/projects/ProjectTaskConfigServlet.java
Fix bug  #110 
the template could not access the type of the task
=> Issues#110

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/api/TimeboardSubjects.java, core/src/main/java/timeboard/core/api/UserService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/internal/UserServiceImpl.java, core/src/main/java/timeboard/core/model/AbstractTask.java, core/src/main/java/timeboard/core/model/Project.java, core/src/main/java/timeboard/core/model/Task.java, core/src/main/java/timeboard/core/model/TaskRevision.java, core/src/main/java/timeboard/core/model/User.java, core/src/main/java/timeboard/core/notification/model/TaskEvent.java, core/src/main/java/timeboard/core/notification/model/TimeboardEvent.java, core/src/main/java/timeboard/core/notification/model/TimeboardEventType.java, core/src/main/java/timeboard/core/observers/SendTaskEmail.java, core/src/test/java/timeboard/core/internal/UserServiceImplTest.java, docs/modeling/aws_arch.graphml, plugins/project-xls-export-plugin/src/main/java/timeboard/plugin/project/export/xls/XlsExportPlugin.java, projects/src/main/java/timeboard/projects/ProjectImportServlet.java, projects/src/main/java/timeboard/projects/ProjectTaskConfigServlet.java, projects/src/main/java/timeboard/projects/ProjectsTasksRESTApi.java, projects/src/main/resources/templates/details_project_config.html, projects/src/main/resources/templates/details_project_tasks_config.html, sample-data/src/main/java/timeboard/sample/TaskLoader.java, scripts/aws/env.yml, scripts/aws/pic.yml, scripts/sql/mysql8.sql, security/src/main/java/timeboard/security/SigninServlet.java, timesheet/src/main/java/timeboard/timesheet/TimesheetRESTApi.java, timesheet/src/main/java/timeboard/timesheet/TimesheetServlet.java, timesheet/src/main/java/timeboard/timesheet/TimesheetTaskCreationRESTApi.java
=> Issues#132

core/src/main/java/timeboard/core/api/ProjectDashboard.java, core/src/main/java/timeboard/core/api/UpdatedTaskResult.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, plugins/project-msp-export-plugin/src/main/java/timeboard/plugin/project/export/msp/MspExportPlugin.java, plugins/project-xls-export-plugin/src/main/java/timeboard/plugin/project/export/xls/XlsExportPlugin.java, projects/src/main/java/timeboard/projects/ProjectTaskConfigServlet.java, projects/src/main/java/timeboard/projects/ProjectsTasksRESTApi.java, projects/src/main/resources/templates/details_project_dashboard.html, projects/src/main/resources/templates/details_project_tasks_config.html, projects/src/main/resources/templates/details_project_tasks_validation.html, timesheet/src/main/java/timeboard/timesheet/TimesheetRESTApi.java, timesheet/src/main/java/timeboard/timesheet/TimesheetServlet.java, timesheet/src/main/java/timeboard/timesheet/TimesheetTaskCreationRESTApi.java, timesheet/src/main/resources/static/timesheet.js, timesheet/src/main/resources/templates/timesheet.html
=> Issues#139

core/src/main/java/timeboard/core/api/ProjectTasks.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/java/timeboard/projects/ProjectTaskConfigServlet.java, projects/src/main/resources/templates/details_project_tasks_config.html, timesheet/src/main/java/timeboard/timesheet/TimesheetRESTApi.java, timesheet/src/main/resources/templates/timesheet.html
=> Issues#142

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/java/timeboard/projects/ProjectTaskConfigServlet.java, projects/src/main/resources/templates/details_project_tasks_config.html
=> Issues#144

projects/src/main/java/timeboard/projects/ProjectTaskDeleteServlet.java
=> Issues#146

README.md, docs/selfSignedCertProcedure.md, features/src/main/feature/feature.xml
=> Issues#147

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java
=> Issues#136

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, shell/src/main/java/timeboard/shell/AddTaskTypeCommand.java
=> Issues #114

core-ui/src/main/java/timeboard/core/ui/TimeboardServlet.java, projects/src/main/java/timeboard/projects/ProjectMilestoneDeleteServlet.java, projects/src/main/java/timeboard/projects/ProjectTaskDeleteServlet.java, projects/src/main/java/timeboard/projects/ProjectTaskListServlet.java
=> Issues#149

features/src/main/feature/feature.xml, pom.xml, reporting/pom.xml, reporting/src/main/java/timeboard/reporting/ReportingNavigationProvider.java, reporting/src/main/java/timeboard/reporting/ReportingServlet.java, reporting/src/main/resources/templates/reporting.html
=> Issues#164

core/src/main/java/timeboard/core/api/TimesheetService.java, core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java, home/src/main/java/timeboard/ui/HomeServlet.java
=> Issues#155

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/model/AbstractTask.java, timesheet/src/main/resources/static/timesheet.js
=> Issues#173

projects/src/main/java/timeboard/projects/TasksRestAPI.java, projects/src/main/resources/static/tasks.js, projects/src/main/resources/templates/details_project_tasks.html, projects/src/main/resources/templates/details_project_tasks_config.html
=> Issues#176

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/model/AbstractTask.java, projects/src/main/java/timeboard/projects/TasksRestAPI.java
=> Issues#177B

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/java/timeboard/projects/ProjectTaskListServlet.java, projects/src/main/resources/templates/details_project_tasks.html
=> Issues#172

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/model/Project.java, projects/src/main/java/timeboard/projects/ProjectOperationsController.java, projects/src/main/resources/templates/projects.html
=> replace delete by archive

core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java
=> Issues#206

core-ui/src/main/resources/templates/fragments/navigation.html, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/model/ProjectMembership.java
=> Issues#211

projects/src/main/resources/templates/details_project_tasks.html
=> Issues#207

core/pom.xml, core/src/main/java/timeboard/core/CoreConfiguration.java, core/src/main/java/timeboard/core/api/exceptions/CommercialException.java, core/src/main/java/timeboard/core/api/exceptions/GlobalExceptionController.java, core/src/main/java/timeboard/core/api/exceptions/resources/commercial_error.html, core/src/main/java/timeboard/core/internal/BusinessPolicyEvaluator.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/java/timeboard/projects/ProjectCreateServlet.java, webapp/src/main/resources/application.properties
=> Issues#193

core-ui/src/main/resources/templates/fragments/navigation.html, organizations/src/main/java/timeboard/timesheet/OrganizationConfigServlet.java, webapp/src/main/java/timeboard/webapp/WebConfig.java
=> Issues#233

organizations/src/main/resources/static/js/org_members.js, projects/src/main/java/timeboard/projects/UsersSearchRestController.java, projects/src/main/resources/static/js/tasks.js, projects/src/main/resources/templates/details_project_config.html
=> Issues#241

account/src/main/java/timeboard.account/AccountConfiguration.java, account/src/main/java/timeboard.account/AccountController.java, account/src/main/java/timeboard.account/TasExportController.java, core-ui/src/main/java/timeboard/core/ui/CoreUIConfiguration.java, home/src/main/java/timeboard/home/HomeConfiguration.java, home/src/main/java/timeboard/home/HomeController.java, organizations/src/main/java/timeboard/timesheet/OrganizationConfigController.java, organizations/src/main/java/timeboard/timesheet/OrganizationCreateController.java, organizations/src/main/java/timeboard/timesheet/OrganizationMembersController.java, organizations/src/main/java/timeboard/timesheet/OrganizationsConfiguration.java, projects/src/main/java/timeboard/projects/ProjectImportController.java, projects/src/main/java/timeboard/projects/ProjectsConfiguration.java, reporting/src/main/java/timeboard/reporting/ReportingConfiguration.java, reporting/src/main/java/timeboard/reporting/ReportingController.java, timesheet/src/main/java/timeboard/timesheet/TimesheetConfiguration.java, timesheet/src/main/java/timeboard/timesheet/TimesheetController.java
=> Issues#244

core-ui/src/main/resources/templates/fragments/navigation.html, home/src/main/resources/templates/home.html, projects/src/main/java/timeboard/projects/ProjectsController.java, projects/src/main/resources/templates/details_project_milestones_config.html, projects/src/main/resources/templates/projects.html, webapp/src/main/java/timeboard/webapp/WebRessourcesInterceptor.java
=> Issues#249

timesheet/src/main/resources/templates/timesheet.html
=> Issues#254

projects/src/main/resources/templates/projects.html
=> Issues#256

core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java, timesheet/src/main/java/timeboard/timesheet/TimesheetController.java, timesheet/src/main/java/timeboard/timesheet/TimesheetRESTApi.java, timesheet/src/main/resources/static/timesheet.js, timesheet/src/main/resources/templates/timesheet.html
=> Issues#242

core/src/main/java/timeboard/core/model/Account.java, core/src/main/java/timeboard/core/model/DataTableConfig.java, core/src/main/java/timeboard/core/model/Milestone.java, core/src/main/java/timeboard/core/model/Project.java, core/src/main/java/timeboard/core/model/StringListToStringConverter.java, core/src/main/java/timeboard/core/model/converters/JSONToProjectAttributsConverter.java, core/src/main/java/timeboard/core/model/converters/JSONToStringListConverter.java, core/src/main/java/timeboard/core/model/converters/JSONToStringMapConverter.java, scripts/sql/mysql8.sql
=> Issues#266

projects/src/main/java/timeboard/projects/TasksRestController.java
=> Issues#265

core-ui/src/main/resources/static/timeboard/js/general.js, core-ui/src/main/resources/templates/fragments/navigation.html, core-ui/src/main/resources/templates/layouts/general.html, eb.sh, webapp/src/main/java/timeboard/webapp/WebRessourcesInterceptor.java, webapp/src/main/resources/application.properties
=> Issues#275

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/api/TimesheetService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java, core/src/main/java/timeboard/core/internal/events/TimesheetEvent.java, core/src/main/java/timeboard/core/model/Project.java, timesheet/src/main/java/timeboard/organization/TimesheetController.java, timesheet/src/main/java/timeboard/organization/TimesheetRESTApi.java
=> Issues#304

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/model/Task.java, projects/src/main/java/timeboard/projects/TasksRestController.java
=> Issues#296

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/java/timeboard/projects/TasksRestController.java, timesheet/src/main/java/timeboard/organization/TimesheetController.java, timesheet/src/main/resources/static/timesheet.js, timesheet/src/main/resources/templates/timesheet.html
=> Issues#311

core-ui/src/main/resources/static/timeboard/js/modal.js, projects/src/main/java/timeboard/projects/ProjectsController.java, projects/src/main/resources/static/js/project_list.js, projects/src/main/resources/static/js/project_tags.js, projects/src/main/resources/static/js/project_tasks.js, projects/src/main/resources/templates/project_tags.html, projects/src/main/resources/templates/project_tasks.html, projects/src/main/resources/templates/projects.html
=> Issues#267

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/resources/policy.json
=> Issues#331

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/resources/templates/projects.html
=> Issues#332

projects/src/main/resources/templates/projects.html
=> Issues#354

core/src/main/java/timeboard/core/model/Account.java, home/src/main/java/timeboard/home/HomeController.java, integ-tests/pom.xml, integ-tests/src/test/java/timeboard/webapp/CucumberTest.java, integ-tests/src/test/java/timeboard/webapp/HomeFeatureATest.java, integ-tests/src/test/java/timeboard/webapp/HomeFeatureBTest.java, integ-tests/src/test/java/timeboard/webapp/TimeboardTest.java, integ-tests/src/test/java/timeboard/webapp/TimeboardWebSecurityConfigForTest.java, integ-tests/src/test/resources/application.properties, integ-tests/src/test/resources/home.feature, pom.xml, projects/src/main/java/timeboard/projects/ProjectTasksSyncController.java, scripts/sql/mysql8.sql, webapp/src/main/resources/application.properties
Sample integration test with cucumber
=> Integration Test

projects/src/main/java/timeboard/projects/ProjectSnapshotsController.java
=> Issues#366

core/src/main/java/timeboard/core/model/Project.java, projects/src/main/java/timeboard/projects/UsersSearchRestController.java, vacations/src/main/resources/static/js/vacations.js
=> Issues#327

home/src/main/java/timeboard/home/HomeNavigationProvider.java, projects/src/main/java/timeboard/projects/ProjectsNavigationProvider.java, reports/src/main/java/timeboard/reports/ReportsNavigationProvider.java, timesheet/src/main/java/timeboard/organization/TimesheetNavigationProvider.java, timesheet/src/main/resources/templates/timesheet.html, vacations/src/main/java/timeboard/vacations/VacationNavigationProvider.java, webapp/src/main/java/timeboard/webapp/TimeboardWebMVCConfig.java, webapp/src/main/resources/i18n/messages_en_EN.properties, webapp/src/main/resources/i18n/messages_fr_FR.properties, webapp/src/main/resources/templates/fragments/navigation.html, webapp/src/main/resources/templates/layouts/general.html
=> add i18n setup with sample config

webapp/src/main/resources/application.properties
=> Number of connexions is configurable

vacations/src/main/java/timeboard/vacations/VacationsController.java, vacations/src/main/resources/static/js/vacations.js, vacations/src/main/resources/templates/vacations.html
=> Issues#373

organizations/src/main/resources/static/js/org_config.js, organizations/src/main/resources/templates/org_config.html
=> Issues#372

reports/src/main/resources/static/js/reports.js
=> Issues#374

core/src/main/java/timeboard/core/internal/EmailServiceImpl.java, core/src/main/java/timeboard/core/internal/observers/emails/SendSummaryEmail.java, webapp/src/main/resources/application.properties
=> Issues#370

account/src/main/java/timeboard.account/AccountController.java, core/src/main/java/timeboard/core/api/OrganizationService.java, core/src/main/java/timeboard/core/api/TimesheetService.java, core/src/main/java/timeboard/core/internal/OrganizationServiceImpl.java, core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java, core/src/main/java/timeboard/core/internal/UserServiceImpl.java, core/src/main/java/timeboard/core/model/Account.java, core/src/main/java/timeboard/core/model/OrganizationMembership.java, integ-tests/src/test/java/timeboard/webapp/OrganizationsTest.java, integ-tests/src/test/java/timeboard/webapp/SecurityUtils.java, integ-tests/src/test/resources/application.properties, organizations/src/main/java/timeboard/organization/OrganizationsRestAPI.java, organizations/src/main/resources/static/js/org_config.js, organizations/src/main/resources/static/js/org_members.js, organizations/src/main/resources/templates/org_members.html, sample-data/src/main/java/timeboard/sample/UserLoader.java, scripts/sql/mysql8.sql, timesheet/src/main/java/timeboard/organization/TimesheetController.java, timesheet/src/main/java/timeboard/organization/TimesheetRESTApi.java, timesheet/src/main/resources/templates/timesheet.html, webapp/src/main/java/timeboard/webapp/CachingConfig.java
=> Issues#371

core/src/main/java/timeboard/core/model/Project.java, projects/src/main/java/timeboard/projects/ProjectsController.java, projects/src/main/resources/templates/create_project.html, scripts/sql/mysql8.sql
=> Issues#390

timesheet/src/main/resources/static/timesheet.js
=> Issues#396

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java
=> Issues#395

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/internal/UserServiceImpl.java, core/src/main/java/timeboard/core/security/TimeboardAuthentication.java, core/src/main/resources/policy.json, integ-tests/src/test/java/timeboard/webapp/ProjectsTest.java, projects/src/main/java/timeboard/projects/ProjectSetupController.java, projects/src/main/java/timeboard/projects/ProjectsController.java, projects/src/main/resources/static/js/project_config.js, projects/src/main/resources/templates/project_config.html
=> Issues#220

home/src/main/java/timeboard/home/HomeController.java, home/src/main/java/timeboard/home/model/WeekWrapper.java, home/src/main/resources/templates/home.html
=> Issues#368

projects/src/main/resources/static/js/project_batches.js, projects/src/main/resources/static/js/project_list.js, projects/src/main/resources/static/js/project_snapshots.js, projects/src/main/resources/static/js/project_tags.js, projects/src/main/resources/templates/project_batches.html, projects/src/main/resources/templates/project_snapshots.html, projects/src/main/resources/templates/project_tags.html, projects/src/main/resources/templates/projects.html, reports/src/main/resources/static/js/reports.js, reports/src/main/resources/templates/reports.html, vacations/src/main/resources/static/js/vacations.js, vacations/src/main/resources/templates/vacations.html
=> Issues#408

timesheet/src/main/resources/templates/timesheet.html
=> Issues#414

timesheet/src/main/java/timeboard/organization/TimesheetController.java, timesheet/src/main/resources/templates/timesheet.html
=> Cacher le template d'input en cas de task in pending

account/src/main/java/timeboard.account/AccountController.java, account/src/main/resources/templates/account.html
=> Issues#413

timesheet/src/main/java/timeboard/organization/TimesheetController.java, timesheet/src/main/resources/static/timesheet.js, timesheet/src/main/resources/templates/timesheet.html
=> Issues#432

account/src/main/java/timeboard.account/AccountController.java, account/src/main/resources/templates/account.html, core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/api/sync/RemoteTask.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/internal/async/ProjectSyncJob.java, core/src/main/java/timeboard/core/model/Task.java, plugins/project-github-import-plugin/src/main/java/timeboard/plugin/project/sync/github/GithubImportPlugin.java, projects/src/main/java/timeboard/projects/ProjectTasksController.java, projects/src/main/java/timeboard/projects/TasksRestAPI.java, projects/src/main/resources/static/js/project_tasks.js, projects/src/main/resources/templates/project_tasks.html, webapp/src/main/resources/public/js/calendar.js
=> Issues#133

timesheet/src/main/resources/static/timesheet.js, timesheet/src/main/resources/templates/timesheet.html
=> Issues#339

timesheet/src/main/java/timeboard/organization/TimesheetController.java, timesheet/src/main/resources/templates/timesheet.html
=> Issues#410

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java, core/src/main/java/timeboard/core/internal/organization/OrganizationServiceImpl.java, core/src/main/java/timeboard/core/model/AbstractTask.java, core/src/main/java/timeboard/core/model/Project.java, integ-tests/pom.xml, integ-tests/src/test/java/timeboard/webapp/CucumberTest.java, integ-tests/src/test/java/timeboard/webapp/GlobalStepDefinitions.java, integ-tests/src/test/java/timeboard/webapp/HomeFeatureATest.java, integ-tests/src/test/java/timeboard/webapp/HomeFeatureBTest.java, integ-tests/src/test/java/timeboard/webapp/OrganizationsTest.java, integ-tests/src/test/java/timeboard/webapp/ProjectFeatureATest.java, integ-tests/src/test/java/timeboard/webapp/ProjectsTest.java, integ-tests/src/test/java/timeboard/webapp/TaskFeatureATest.java, integ-tests/src/test/java/timeboard/webapp/TimeboardTest.java, integ-tests/src/test/java/timeboard/webapp/TimeboardWorld.java, integ-tests/src/test/java/timeboard/webapp/TimesheetFeatureTest.java, integ-tests/src/test/resources/application.properties, integ-tests/src/test/resources/home.feature, integ-tests/src/test/resources/projects.feature, integ-tests/src/test/resources/tasks.feature, integ-tests/src/test/resources/timesheet.feature, projects/src/main/java/timeboard/projects/ProjectsController.java
=> Issues#453 (cucumber tests)

timesheet/src/main/java/timeboard/organization/TimesheetController.java, timesheet/src/main/resources/static/timesheet.js, timesheet/src/main/resources/templates/timesheet.html, webapp/src/main/resources/i18n/messages_en.properties
=> Issues#440

core/src/main/java/timeboard/core/CoreConfiguration.java, core/src/main/java/timeboard/core/security/TimeboardAuthentication.java, integ-tests/src/test/resources/application.properties, organizations/src/main/java/timeboard/organization/OrganizationSelectController.java, organizations/src/main/resources/templates/org_select.html, webapp/src/main/resources/application.properties
=> Issues#452

projects/src/main/resources/templates/projects.html
=> Issues#459

account/src/main/resources/templates/account.html
=> Issues#465

projects/src/main/resources/templates/project_layout.html
=> Issues#471

projects/src/main/java/timeboard/projects/ProjectTasksController.java, projects/src/main/java/timeboard/projects/TasksRestAPI.java, projects/src/main/resources/static/js/project_tasks.js, projects/src/main/resources/templates/project_tasks.html
=> Issues#474

core/src/main/java/timeboard/core/model/Batch.java, projects/src/main/java/timeboard/projects/ProjectTasksController.java, projects/src/main/resources/templates/project_tasks.html
#472
Quick and diry solution for v1
Vu avec @Jean-GuillaumeT
=> Issues#472

webapp/src/main/resources/public/js/calendar.js
=> Issues#470

timesheet/src/main/resources/templates/timesheet.html
=> Issues#458

timesheet/src/main/resources/templates/timesheet.html
=> Issues#485

timesheet/src/main/resources/static/timesheet.js
=> Issues#463

projects/src/main/java/timeboard/projects/ProjectSetupController.java, projects/src/main/resources/static/js/project_tasks.js
=> Issues#462

account/src/main/resources/templates/account.html, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, core/src/main/java/timeboard/core/security/AbacEntries.java, core/src/main/resources/policy-set.json
=> Edit policy to disable some features for v1

timesheet/src/main/resources/static/timesheet.js, timesheet/src/main/resources/templates/timesheet.html, webapp/src/main/java/timeboard/webapp/DataTableConfigRestController.java
=> Issues#477

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/java/timeboard/projects/ProjectBatchesController.java
=> Issues#491

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, reports/src/main/java/timeboard/reports/ProjectDashboardController.java, reports/src/main/resources/static/js/project_dashboard.js, reports/src/main/resources/templates/project_dashboard.html
=> Issues#475

timesheet/src/main/resources/templates/timesheet.html
=> Issues#497

core/src/main/java/timeboard/core/api/BusinessPolicyEvaluator.java, core/src/main/java/timeboard/core/internal/BusinessPolicyEvaluatorImpl.java, core/src/main/java/timeboard/core/security/BasicPolicyEnforcement.java, core/src/main/java/timeboard/core/security/PolicyEnvironment.java, core/src/main/resources/policy-set.json, integ-tests/src/test/resources/application.properties, projects/src/main/resources/templates/projects.html, webapp/src/main/resources/application.properties
=> Issues#457

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/java/timeboard/projects/ProjectTasksController.java, projects/src/main/java/timeboard/projects/TasksRestAPI.java, projects/src/main/resources/templates/project_tasks.html
=> Issues#476

projects/src/main/java/timeboard/projects/ProjectBaseController.java, projects/src/main/java/timeboard/projects/ProjectBatchesNavigationProvider.java, projects/src/main/java/timeboard/projects/ProjectSetupNavigationProvider.java, projects/src/main/java/timeboard/projects/ProjectSnapshotsNavigationProvider.java, projects/src/main/java/timeboard/projects/ProjectTagsNavigationProvider.java, projects/src/main/java/timeboard/projects/ProjectTasksNavigationProvider.java, projects/src/main/java/timeboard/projects/ProjectTeamCalendarNavigationProvider.java, projects/src/main/java/timeboard/projects/api/ProjectNavigationProvider.java, reports/src/main/java/timeboard/reports/ProjectDashboardNavigationProvider.java, timesheet/src/main/java/timeboard/organization/TimesheetProjectNavigationProvider.java
=> Issues#496

projects/src/main/resources/static/js/project_snapshots.js, projects/src/main/resources/static/js/project_tasks.js, projects/src/main/resources/templates/project_snapshots.html, projects/src/main/resources/templates/project_tasks.html, reports/src/main/resources/static/js/project_dashboard.js, reports/src/main/resources/templates/project_dashboard.html
=> Issues#490

timesheet/src/main/resources/static/timesheet.js, timesheet/src/main/resources/templates/timesheet.html
=> Issues#501

timesheet/src/main/resources/templates/timesheet.html
=> Issues#505

core/src/main/java/timeboard/core/security/AbacEntries.java, core/src/main/java/timeboard/core/security/TimeboardAuthentication.java, core/src/main/resources/policy-set.json, organizations/src/main/java/timeboard/organization/ImpersonationController.java, organizations/src/main/java/timeboard/organization/OrganizationMembersController.java, organizations/src/main/resources/static/js/org_members.js, organizations/src/main/resources/templates/org_members.html, webapp/src/main/java/timeboard/webapp/WebRessourcesInterceptor.java, webapp/src/main/resources/templates/layouts/general.html
=> Issues#507

projects/src/main/resources/templates/project_calendar.html
=> Issues#514

projects/src/main/resources/templates/projects.html
=> Issues#515

organizations/src/main/java/timeboard/organization/OrganizationMembersController.java, organizations/src/main/resources/static/js/org_members.js, organizations/src/main/resources/templates/org_members.html, projects/src/main/java/timeboard/projects/UsersSearchRestController.java
#519
- Réparation ajout / suppression de membre
- Ajout d'un confirmation à la suppression d'un membre
- Recherche d'utilisateur dans l'application via l'exact mail
=> Issues#519

projects/src/main/resources/templates/project_calendar.html
=> Issues#522

vacations/src/main/resources/templates/vacations.html
=> Issues#526

organizations/src/main/java/timeboard/timesheet/OrganizationConfigController.java, projects/src/main/resources/templates/project_tasks.html
=> Issues#532

account/src/main/resources/templates/account.html
=> Issues#537

core/src/main/java/timeboard/core/internal/TimesheetServiceImpl.java, home/src/main/java/timeboard/home/HomeController.java
=> Issues#528

home/src/main/resources/templates/home.html, organizations/src/main/resources/templates/org_config.html, organizations/src/main/resources/templates/org_members.html, projects/src/main/resources/templates/create_project.html, projects/src/main/resources/templates/project_batches.html, projects/src/main/resources/templates/project_calendar.html, projects/src/main/resources/templates/project_setup.html, projects/src/main/resources/templates/project_snapshots.html, projects/src/main/resources/templates/project_tags.html, projects/src/main/resources/templates/project_tasks.html, projects/src/main/resources/templates/projects.html, reports/src/main/resources/templates/create_report.html, reports/src/main/resources/templates/project_dashboard.html, reports/src/main/resources/templates/report_layout.html, reports/src/main/resources/templates/reports.html, timesheet/src/main/resources/templates/timesheet_validation.html, vacations/src/main/resources/templates/vacations.html, webapp/src/main/resources/i18n/messages_en.properties
=> Issues#535

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java
=> Issues#529

projects/src/main/java/timeboard/projects/ProjectTasksController.java, projects/src/main/java/timeboard/projects/TasksRestAPI.java
=> Issues#513

core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/resources/static/js/project_tasks.js
=> Issues#536

projects/src/main/java/timeboard/projects/ProjectTasksController.java, projects/src/main/java/timeboard/projects/TasksRestAPI.java, projects/src/main/resources/templates/project_tasks.html
=> Issues#539

timesheet/src/main/java/timeboard/timesheet/TimesheetController.java, timesheet/src/main/resources/templates/timesheet.html
=> Issues#543

reports/src/main/resources/templates/project_dashboard.html
=> Issues#545

organizations/src/main/resources/templates/org_select.html
=> Issues#553

core/src/main/java/timeboard/core/model/CalendarEvent.java, core/src/main/java/timeboard/core/model/Event.java, docs/vue-component/calendar.md, docs/vue-component/data-table.md, webapp/src/main/resources/public/js/calendar.js, webapp/src/main/resources/public/js/datatable.js
=> Issues#559

core/src/main/java/timeboard/core/api/VacationService.java, core/src/main/java/timeboard/core/internal/VacationServiceImpl.java, docs/vue-component/calendar.md, integ-tests/src/test/java/timeboard/webapp/TaskFeatureATest.java, integ-tests/src/test/java/timeboard/webapp/VacationsFeatureTest.java, integ-tests/src/test/resources/vacations.feature
=> Issues#552

core/src/main/java/timeboard/core/api/ProjectService.java, core/src/main/java/timeboard/core/internal/ProjectServiceImpl.java, projects/src/main/java/timeboard/projects/UsersSearchRestController.java
=> Issues#563

integ-tests/src/test/resources/application.properties, webapp/src/main/resources/application.properties
=> Issues#571

organizations/src/main/java/timeboard/timesheet/OrganizationMembersController.java, organizations/src/main/resources/static/js/org_members.js, organizations/src/main/resources/templates/org_members.html
=> Issues#554

integ-tests/src/test/java/timeboard/webapp/GlobalStepDefinitions.java, integ-tests/src/test/java/timeboard/webapp/ProjectFeatureATest.java, integ-tests/src/test/java/timeboard/webapp/TaskFeatureTest.java, integ-tests/src/test/resources/projects.feature, integ-tests/src/test/resources/tasks.feature, projects/src/main/java/timeboard/projects/ProjectSetupController.java
=> Issues#577

core/src/main/java/timeboard/core/api/BusinessPolicyEvaluator.java, core/src/main/java/timeboard/core/internal/BusinessPolicyEvaluatorImpl.java, core/src/main/java/timeboard/core/security/PolicyEnvironment.java, core/src/main/resources/policy-set.json, integ-tests/src/test/resources/application.properties, organizations/src/main/resources/templates/org_select.html, projects/src/main/java/timeboard/projects/ProjectsController.java, projects/src/main/resources/templates/projects.html, webapp/src/main/resources/application.properties
=> Issues#574

core/src/main/java/timeboard/core/api/ReportService.java, core/src/main/java/timeboard/core/internal/reports/LocalSecurityContext.java, core/src/main/java/timeboard/core/internal/reports/ReportJob.java, core/src/main/java/timeboard/core/internal/reports/ReportServiceImpl.java, core/src/main/java/timeboard/core/model/Organization.java, core/src/main/java/timeboard/core/model/OrganizationMembership.java, core/src/main/java/timeboard/core/model/ProjectAttributValue.java, core/src/main/java/timeboard/core/model/ProjectMembership.java, reports/src/main/java/timeboard/reports/ReportsController.java, reports/src/main/resources/static/js/reports.js, reports/src/main/resources/templates/reports.html
=> Issues#584
